
agent.sources = kafka-source
agent.channels = memory-channel
agent.sinks = hdfs-sink

# ----- Kafka Source -----
agent.sources.kafka-source.type = org.apache.flume.source.kafka.KafkaSource
agent.sources.kafka-source.kafka.bootstrap.servers = 192.168.32.100:9092
agent.sources.kafka-source.kafka.topics = user_behavior
agent.sources.kafka-source.kafka.consumer.group.id = flume-consumer-group
agent.sources.kafka-source.batchSize = 100
agent.sources.kafka-source.batchDurationMillis = 2000


agent.sources.kafka-source.interceptors = i1
agent.sources.kafka-source.interceptors.i1.type = timestamp

# ----- Memory Channel -----
agent.channels.memory-channel.type = memory
agent.channels.memory-channel.capacity = 10000
agent.channels.memory-channel.transactionCapacity = 1000

# ----- HDFS Sink -----
agent.sinks.hdfs-sink.type = hdfs
agent.sinks.hdfs-sink.hdfs.path = hdfs://mycluster/data/original/behavior/dt=%Y-%m-%d/hour=%H
agent.sinks.hdfs-sink.hdfs.filePrefix = events
agent.sinks.hdfs-sink.hdfs.fileSuffix = .log
agent.sinks.hdfs-sink.hdfs.useLocalTimeStamp = true   
agent.sinks.hdfs-sink.hdfs.rollInterval = 60          
agent.sinks.hdfs-sink.hdfs.rollSize = 134217728       
agent.sinks.hdfs-sink.hdfs.rollCount = 0              
agent.sinks.hdfs-sink.hdfs.batchSize = 100
agent.sinks.hdfs-sink.hdfs.writeFormat = Text
agent.sinks.hdfs-sink.hdfs.fileType = DataStream


agent.sources.kafka-source.channels = memory-channel
agent.sinks.hdfs-sink.channel = memory-channel